name: adrus
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.1
  connectivity: ^3.0.3
  shared_preferences: ^2.0.5 
  intl: ^0.17.0
  fluttertoast: ^8.0.3
  rxdart: ^0.26.0
  flutter_svg: ^0.21.0+1
  get_it: ^6.1.0
  json_annotation: ^4.0.1
  image_picker: ^0.7.4
  carousel_slider: ^3.0.0
  flutter_share: ^2.0.0
  visibility_detector: ^0.2.0
  flutter_phoenix: ^1.0.0
  path_provider: ^2.0.1
  dio: ^4.0.0
  universal_html: ^2.0.8
  url_launcher: ^6.0.3
  flutter_offline: ^2.0.0
  flutter_facebook_login: ^3.0.0 
  google_sign_in: ^5.0.1
  firebase_auth: ^1.0.3
  firebase_core: ^1.0.3
  firebase_analytics: ^7.1.1
  flutter_riverpod: ^0.14.0+1
  toast: ^0.1.5
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^5.0.0
  cached_network_image: ^3.0.0
  awesome_loader: ^0.0.3
  assets_audio_player: ^3.0.3+2
  fcm_config: ^3.0.4
  fijkplayer:
    git:
      url: https://github.com/ibrahimnashat/player.git  
  #flutter_launch: ^0.2.0
  #apple_sign_in: ^0.1.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icon/
    - assets/images/icon/png/
    - assets/titireretiti.mp3

  fonts:
    - family: Bahij
      fonts:
        - asset: assets/fonts/Bahij-Regular.ttf
          weight: 600
        - asset: assets/fonts/Bahij-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Bahij-Bold.ttf
          weight: 900
